name: "\U0001F5BC Prompt"
description: Prompt for a new image (title)
title: "Your prompt here"
labels: ["prompt"]
assignees: []
body:
    - type: markdown
      attributes:
          value: Use the title to create a prompt for a new image
