name: "\U0001F5BC Prompt"
description: Prompt for a new image
title: "Your prompt here"
labels: ["prompt"]
assignees: []
body:
    - type: dropdown
      attributes:
          label: Size
          description: Smaller size generate faster
          options:
              - 256x256
              - 512x512
              - 1024x1024
