name: "\U0001F5BC Prompt"
description: Prompt for a new image
labels: ["prompt"]
assignees: []
body:
    - type: dropdown
      attributes:
          label: Size
          description: A smaller image generate faster
          options:
              - 512x512
              - 1024x1024
    - type: checkboxes
      attributes:
          label: Notice
          options:
              - label: Confirm that the prompt doesn't contain any offensive content
                required: true
    - type: markdown
      attributes:
          value: |
              It will take few seconds to generate the new image.
