name: Generate image

on:
    push:
        branches:
            - main
    issues:
        types: [opened]

env:
    node_version: "18.x"

jobs:
    generate-image:
        runs-on: ubuntu-latest
        steps:
          - name: Generate image
            uses: actions/checkout@v3
            uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.node_version }}
            run: |
              touch .env
              echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env
              echo OPENAI_PROMPT=${{ github.event.issue.title }} >> .env
              echo GITHUB_USERNAME=${{ github.event.issue.user.login }} >> .env
              npm install
              npm run start
          - name: Push new README.md
            uses: mikeal/publish-to-github-action@master
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
