name: Generate image

on:
    push:
        branches:
            - main
    issues:
        types: [opened]

env:
    node_version: "18.x"
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    OPENAI_PROMPT: ${{ github.event.issue.title }}
    GITHUB_USERNAME: ${{ github.event.issue.user.login }}

jobs:
    generate-image:
        name: Generate image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.node_version }}
            - run: npm install
            - run: npm run start
