name: Generate image

on:
    issues:
        types: [opened]

env:
    node_version: "18.x"

jobs:
    generate-image:
        runs-on: ubuntu-latest
        steps:
            - name: Generate image
              uses: actions/checkout@v3
            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.node_version }}
            - name: Generate env file
              run: |
                  touch .env
                  echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env
                  echo OPENAI_PROMPT=${{ github.event.issue.title }} >> .env
                  echo OPENAI_OPTION_SIZE=1024x1024 >> .env
                  echo GITHUB_ISSUE_ID=${{ github.event.issue.id }} >> .env
                  echo GITHUB_USERNAME=${{ github.event.issue.user.login }} >> .env
            - name: Install dependencies
              run: npm install
            - name: start
              run: npm run start
            - name: Push new README.md
              uses: mikeal/publish-to-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH_NAME: main
