name: Generate image

on:
    issues:
        types: [labeled]

env:
    node_version: "18.x"

jobs:
    generate-image:
        if: github.event.label.name == 'prompt'
        runs-on: ubuntu-latest
        steps:
            - name: Generate image
              uses: actions/checkout@v3
            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.node_version }}
            - name: Generate env file
              run: |
                  touch .env
                  echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env
                  echo OPENAI_PROMPT=${{ github.event.issue.title }} >> .env
                  echo OPENAI_OPTION_SIZE=1024x1024 >> .env
                  echo GITHUB_ISSUE_NUMBER=${{ github.event.issue.number }} >> .env
                  echo GITHUB_USERNAME=${{ github.event.issue.user.login }} >> .env
            - name: Install dependencies
              run: npm install
            - name: start
              run: npm run start
            - name: Push new README.md
              uses: mikeal/publish-to-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH_NAME: main
            - name: Create comment
              uses: peter-evans/create-or-update-comment@v2
              with:
                  issue-number: ${{ github.event.issue.number }}
                  body: |
                      @${{ github.event.issue.user.login }} You can download the generated image at [https://raw.githubusercontent.com/zk-g/zk-g/main/${{ github.event.issue.number }}.png](https://raw.githubusercontent.com/zk-g/zk-g/main/${{ github.event.issue.number }}.png)
