name: Generate image

on:
    discussion:
        types: [created]

env:
    node_version: "18.x"

jobs:
    generate-image:
        if: github.event.discussion.category.name == 'Prompt'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.node_version }}
            - name: Generate env file
              run: |
                  touch .env
                  echo OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" >> .env
                  echo STABLE_DIFFUSION_API_KEY="${{ secrets.STABLE_DIFFUSION_API_KEY }}" >> .env
                  echo PROMPT="${{ github.event.discussion.title }}" >> .env
                  echo -n DISCUSSION_BODY=\" >> .env
                  while IFS= read -r line; do
                      echo -n "$line " >> .env
                  done <<< "${{ github.event.discussion.body }}"
                  echo \" >> .env
                  echo IMAGE_SIZE="1024" >> .env
                  echo GITHUB_DISCUSSION_NUMBER="${{ github.event.discussion.number }}" >> .env
                  echo GITHUB_USERNAME="${{ github.event.discussion.user.login }}" >> .env
            - name: Install dependencies
              run: npm install
            - name: Generate image and write readme
              run: npm run start
            - name: Push new README.md
              uses: mikeal/publish-to-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH_NAME: main
